name: Build and Deploy Artifact
on:
  push:
    branches: release-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: demo-app:latest

      - name: Export Docker image to tar
        run: docker save -o demo-app.tar demo-app:latest

      - name: Upload artifact
        uses: appleboy/scp-action@master
        with:
          host: 54.147.104.114
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: demo-app.tar
          target: /home/ubuntu/demo-app.tar

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.147.104.114
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove existing container (if exists)
            docker stop demo-app || true
            docker rm demo-app || true
            
            # Load Docker image from artifact
            docker load -i /home/ubuntu/demo-app.tar
            
            # Run Docker container
            docker run -d --name demo-app -p 80:80 demo-app:latest
            # end code pipeline2